# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS
# Appserver with 10gb EBS
# One S3 bucket to store invoice pds files

Parameter:
  InstanceTypeParm:
    Type: String
    Default: "t2.micro"
    Description: "Type of instance type to be created"

Resources:
  Webserver:
     Type: AWS::EC2::Instance
     Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: "t2.micro"
      KeyName: "1st@goNOv"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "100"
          DeleteOnTermination: "True"
          VolumeSize: "8"
  Appserver:
     Type: AWS::EC2::Instance
     Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: "t2.micro"
      KeyName: "1st@goNOv"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "100"
          DeleteOnTermination: "True"
          VolumeSize: "10"
  s3InvoiceBucket: 
    Type: AWS::S3::Bucket